/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Contato;
import persistencia.Conexao;
import persistencia.JDBCContato;

/**
 *
 * @author anton
 */
public class Exibir extends javax.swing.JInternalFrame {

    /**
     * Creates new form Exibir
     */
    public Exibir() {
        initComponents();
        Conexao fabrica = new Conexao();
        JDBCContato gerente = new JDBCContato(fabrica.abrirConexao());
        ArrayList<Contato> contatos = gerente.listarContatos();

        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);

        for(Contato c: contatos){
            Object[] dados = {c.getId(), c.getNome(), c.getTelefone()};
            modelo.addRow(dados);
        }
        fabrica.fecharConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelExibir = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jButton4.setText("Apagar Tudo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Apagar Contato");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Atualizar Contato");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        PainelExibir.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PainelExibir.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PainelExibir.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PainelExibir.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PainelExibirLayout = new javax.swing.GroupLayout(PainelExibir);
        PainelExibir.setLayout(PainelExibirLayout);
        PainelExibirLayout.setHorizontalGroup(
            PainelExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelExibirLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PainelExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelExibirLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(59, 59, 59)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        PainelExibirLayout.setVerticalGroup(
            PainelExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelExibirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelExibir)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelExibir, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int apagar = JOptionPane.showConfirmDialog(PainelExibir,"Tem certeza disso?");
        
        switch(apagar){
            case 0:
                Conexao fabrica = new Conexao();
                JDBCContato gerente = new JDBCContato(fabrica.abrirConexao());
                gerente.apagarTudo();
                fabrica.fecharConexao();

                //Apgando a tabela da aplicacao
                DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
                modelo.setNumRows(0);
            break;
            case 1:
            break;
            case 2:
            break;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o id do contato:"));
        Conexao fabrica = new Conexao();
        JDBCContato gerente = new JDBCContato(fabrica.abrirConexao());
        gerente.apagarContato(id);
        fabrica.fecharConexao();
        atualizarTabela();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID do contato:"));
        String telefone = JOptionPane.showInputDialog("Digite o novo telefone:");
        
        Conexao fabrica = new Conexao();
        JDBCContato gerente = new JDBCContato(fabrica.abrirConexao());
        gerente.atualizaContato(telefone, id);
        fabrica.fecharConexao();
        atualizarTabela();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void atualizarTabela(){
        Conexao fabrica = new Conexao();
        JDBCContato gerente = new JDBCContato(fabrica.abrirConexao());
        ArrayList<Contato> contatos = gerente.listarContatos();

        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);

        for(Contato c: contatos){
            Object[] dados = {c.getId(), c.getNome(), c.getTelefone()};
            modelo.addRow(dados);
        }
        fabrica.fecharConexao();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane PainelExibir;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
